stages:
  - check
  - deploy

项目规范检测:
  stage: check
  script:
    - psc --alias xx --notify
  only:
    - branches
  except:
    - master

部署release分支:
  stage: deploy
  cache:
    key: '$CI_COMMIT_REF_NAME'
    paths:
      - dist/
      - app/view/
    policy: pull
  script:
    - cid=`docker ps -a --filter='name=frontend_generate-qrcode_running' -q`
    - if [ ! -z $cid ];then
    - docker rm -f  $cid
    - fi
    - docker build -t frontend/generate-qrcode .

    - DATE_STAMP=${CI_COMMIT_REF_NAME#*/}
    - TAG_NAME=docker.ifchange.com/toc/frontend-generate-qrcode:${DATE_STAMP}
    - docker tag frontend/generate-qrcode $TAG_NAME
    - docker push $TAG_NAME
    - echo "提测镜像地址"$TAG_NAME
    - docker run -d -p 7122:7100 --name=frontend_generate-qrcode_running frontend/generate-qrcode
    - echo "branch $CI_COMMIT_REF_NAME(${CI_COMMIT_SHA:0:7}) is running at http://xx.xx.xx.xx:xx/"
  environment:
    name: development/release
    url: http://xx.xx.x.xx:7100
  #when: manual
  only:
    - /^(release|hotfix)\/.+$/

创建Tag:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - autotag
  only:
    - master
