FROM node:8-alpine

COPY . ./

# RUN apk add --no-cache \
#     cairo cairo-dev cairomm-dev \
#     pango pango-dev pangomm pangomm-dev \
#     build-base \
#     g++ \
#     jpeg-dev \
#     pango-dev \
#     freetype-dev \
#     giflib-dev

RUN apk add --no-cache --virtual .health-check curl \
	&& apk add --no-cache --virtual .build-deps git build-base g++ \
	&& apk add --no-cache --virtual .npm-deps cairo-dev libjpeg-turbo-dev pango
    
RUN npm install

EXPOSE 7001

CMD npm run docker-start
